FROM node:16-alpine

WORKDIR /app

COPY package.json /app

# To Fix Permissions for Packages
RUN npm config set unsafe-perm true

RUN npm install --force

COPY . /app

RUN chmod -R 777  /app/node_modules

CMD ["npm", "run", "start"]